### PR TITLE
multiple project selection in solution explorer

### PR DESCRIPTION
**Pull request by quatmax**
Hi!

This would be the code for multi-project selection in "Solution Explorer".
I didn't changed the behaviour of "Tools"-menu.

Thanks again for this great tool!

BR, max

### CODE REVIEW

**Comment by quatmax** [comment]
The above commit should respect multiple different configurations...

**Comment by quatmax** [comment]
There is a bug now with double-clicking the item in the result window.
I think that the `Problem` parsed from the output can only handle project relative paths.
I will have a look at this...

**Comment by Dmitry-Me** [comment]
Anyway there's no point in two commits - history will be cluttered. You'd have to first "reset" them (`git reset HEAD~2`), then create a separate branch, then commit them back into the new branch and then push that branch and open the PR from there.

**Comment by quatmax** [comment]
Ok, got it!

**Pull request closed without merging**
