### PR TITLE
fix issue Plugin fails to load after installation #138

### PR DESCRIPTION
**Pull request by bugparty**
haha,I got it works in vs2012
here is my release http://rghost.net/75VTbBNgg

### CODE REVIEW

**Comment by Vitaliy-Grigoriev** [comment]
Сan be curious what was the mistake?

**Comment by bugparty** [comment]
I think the problem is the dependence should be mpf not mpf.11

**Comment by VioletGiraffe** [comment]
Thanks!

**Comment by bugparty** [comment]
you are welcome,thanks you for this great software too!

**Pull request merged**
