### PR TITLE
multiple project selection in solution explorer

### PR DESCRIPTION
**Pull request by quatmax**

### CODE REVIEW

**Comment by VioletGiraffe** [comment]
I can't build the project:
`error CS0246: The type or namespace name 'ConfiguredFiles' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Dmitry-Me** [comment]
Looks like the pull request omitted the `ConfiguredFiles` class. I guess all you need is:

    public class ConfiguredFiles {
           public List<SourceFile> Files;
           public Configuration Configuration;
    }

**Comment by VioletGiraffe** [comment]
What's with `is64bitConfiguration` / `isDebugConfiguration` then? Could you please pull the latest revision from my original repository and fix the build?

**Comment by Dmitry-Me** [comment]
Please observe https://github.com/VioletGiraffe/cppcheck-vs-addin/pull/129

**Comment by quatmax** [comment]
Hi! Please excuse my late reply! I've been on leave for the last weeks. Thank you for fixing my stuff...

**Pull request merged**
