### PR TITLE
Multiple projects selection in solution explorer

### PR DESCRIPTION
**Pull request by quatmax**
Hi!

I added multiple selection for project items in "Solution Explorer", therefore I had to refactor the `checkCurrentProject` method...
The logic of checking only the first found project from "Tools" menu is untouched.

BR, max

### CODE REVIEW

**Comment by VioletGiraffe** [comment]
I think you might have broken something in the project settings. I've cloned `quatmax/cppcheck-vs-addin` and I can't debug it. It builds the VSIX, but when I press F5 I get an error message - something about not being able to debug class library projects.
My repository, on the other hand, is also a class library project but can be debugged just fine.

**Comment by Dmitry-Me** [comment]
This change contains whitespaces instead of tabs which means merging it basically trashes the history beyond any recognition.

**Comment by VioletGiraffe** [comment]
Yep, can't see what has actually changed. That's why I wanted to have a look before accepting the request, but couldn't actually launch the experimental VS instance.

**Comment by quatmax** [comment]
@VioletGiraffe 
Hm, I just changed the settings locally, as you recommended in the "readme".
These steps work for me for debugging:
* clone
* open sln in VS2013 -> solution is upgraded
* Project->Settings->Start external program: C:\Program Files (x86)\Microsoft Visual Studio 12.0\common7\IDE\devenv.exe
* Project->Settings->Command line arguments: /RootSuffix Exp

@Dmitry-Me 
I will try to disable automatic formatting and resubmit my patch.

**Comment by VioletGiraffe** [comment]
Also, only tabs in my project please. No spaces for indentation.

**Comment by quatmax** [comment]
OK! I will close this one. Thanks for your patience ;-)

**Comment by VioletGiraffe** [comment]
@quatmax, those additional manipulation are not required in the 2 computers where I've tested this project. Clone, open, upgrade, press F5. That's it.

**Comment by quatmax** [comment]
That's interesting: If I follow your steps and press F5 I get this:

image

So I set the executable as mentioned here: 
https://github.com/VioletGiraffe/cppcheck-vs-addin/blob/master/README.md

**Comment by VioletGiraffe** [comment]
@quatmax: fair enough, perhaps I've set it up long ago and have forgotten about that nuance. Never mind.

**Pull request closed without merging**
