### PR TITLE
Prevent a save prompt when checking files on saving and cppcheck is already running

### PR DESCRIPTION
**Pull request by kinglike1337**

### CODE REVIEW

**Comment by VioletGiraffe** [comment]
Very nice, thank you! But could you clean up those magic ID numbers?

**Comment by kinglike1337** [comment]
Any hints where these magic numbers are defined in the sdk?

**Comment by kinglike1337** [comment]
@VioletGiraffe Done as constants defined in the class.

**Comment by VioletGiraffe** [comment]
Good work, thanks!

**Pull request merged**
