### PR TITLE
Proper and timely release bitmaps

### PR DESCRIPTION
**Pull request by Dmitry-Me**
The "before" code contains a serious resource leak which makes devenv.exe waste two bitmaps for every problem item in the problem list every time the list is populated. This can cause system-wide resource shortage and runtime problems for all processes in the system.

### CODE REVIEW

**Comment by VioletGiraffe** [comment]
What was the problem, exactly? `bitmap.GetHbitmap()` without explicit manual release?

**Comment by Dmitry-Me** [comment]
Yes, `Bitmap.GetHbitmap()` returns `IntPtr` and ownership of the unmanaged object behind this `IntPtr` is passed to the caller.

**Comment by VioletGiraffe** [comment]
I see, didn't expect or notice that.
Is there any reason why C# developers couldn't wrap this handle into a managed object?

**Comment by Dmitry-Me** [comment]
I guess it's a design defect especially we consider the sad fact that we have to P/Invoke a release function after we've obtained the object without using P/Invoke. That's what happens when everyone is busy redesigning Visual Studio UI every version.

**Pull request merged**
